@echo off
echo Installing Capacitor...
npm install --save-dev @capacitor/core @capacitor/cli @capacitor/android

echo Initializing Capacitor...
npx cap init "AI Energy Simulator" com.daikin.energy.simulator

echo Adding Android platform...
npx cap add android

echo Building React app...
npm run build

echo Syncing with Capacitor...
npx cap sync

echo Opening Android Studio...
npx cap open android